const langData = {
    // 한국어
    ko: {
        role: "프리랜서 프로그래머",
        based: "필리핀 거주",
        intro_title: "안녕하세요, 토니 조입니다.",
        intro_desc: "비즈니스의 문제를 해결하는 웹과 앱을 만듭니다. 포트폴리오를 확인해 보세요.",
        btn_all: "전체",
        btn_admin: "관리 도구",
        btn_media: "미디어",
        btn_utility: "유틸리티",
        btn_game: "게임",
        contact_title: "프로젝트 문의",
        contact_desc: "새로운 프로젝트나 협업 제안은 언제나 환영합니다.",
        btn_contact: "이메일 보내기",
        btn_close: "닫기",
        btn_visit: "사이트 방문하기",
        label_name: "성함",
        label_email: "이메일",
        label_message: "내용",
        btn_send: "전송하기"
    },
    // 영어 (기본)
    en: {
        role: "Freelance Programmer",
        based: "Based in Philippines",
        intro_title: "Hello, I'm Tony Cho.",
        intro_desc: "I build web apps that solve real business problems. Check out my works.",
        btn_all: "All",
        btn_admin: "Management",
        btn_media: "Media",
        btn_utility: "Utility",
        btn_game: "Game",
        contact_title: "Get In Touch",
        contact_desc: "Open for new projects and collaborations.",
        btn_contact: "Send Email",
        btn_close: "Close",
        btn_visit: "Visit Site",
        label_name: "Name",
        label_email: "Email",
        label_message: "Message",
        btn_send: "Send Message"
    },
    // 일본어
    ja: {
        role: "フリーランスプログラマー",
        based: "フィリピン在住",
        intro_title: "こんにちは、Tony Choです。",
        intro_desc: "ビジネスの課題を解決するウェブアプリを開発しています。",
        btn_all: "すべて",
        btn_admin: "管理ツール",
        btn_media: "メディア",
        btn_utility: "ユーティリティ",
        btn_game: "ゲーム",
        contact_title: "お問い合わせ",
        contact_desc: "新しいプロジェクトのご相談をお待ちしております。",
        btn_contact: "メールを送る",
        btn_close: "閉じる",
        btn_visit: "サイトへ",
        label_name: "お名前",
        label_email: "メール",
        label_message: "メッセージ",
        btn_send: "送信"
    },
    // 중국어 (간체)
    zh: {
        role: "自由职业程序员",
        based: "常驻菲律宾",
        intro_title: "你好，我是 Tony Cho。",
        intro_desc: "我开发能解决实际业务问题的网络应用程序。",
        btn_all: "全部",
        btn_admin: "管理工具",
        btn_media: "多媒体",
        btn_utility: "实用工具",
        btn_game: "游戏",
        contact_title: "联系我",
        contact_desc: "欢迎咨询新项目与合作。",
        btn_contact: "发送邮件",
        btn_close: "关闭",
        btn_visit: "访问网站",
        label_name: "姓名",
        label_email: "邮箱",
        label_message: "信息",
        btn_send: "发送"
    },
    // 스페인어
    es: {
        role: "Programador Freelance",
        based: "Con base en Filipinas",
        intro_title: "Hola, soy Tony Cho.",
        intro_desc: "Creo aplicaciones web que resuelven problemas reales de negocio.",
        btn_all: "Todo",
        btn_admin: "Gestión",
        btn_media: "Media",
        btn_utility: "Utilidad",
        btn_game: "Juego",
        contact_title: "Contáctame",
        contact_desc: "Abierto a nuevos proyectos.",
        btn_contact: "Enviar Correo",
        btn_close: "Cerrar",
        btn_visit: "Visitar Sitio",
        label_name: "Nombre",
        label_email: "Correo",
        label_message: "Mensaje",
        btn_send: "Enviar"
    },
    // 프랑스어
    fr: {
        role: "Programmeur Freelance",
        based: "Basé aux Philippines",
        intro_title: "Bonjour, je suis Tony Cho.",
        intro_desc: "Je crée des applications web pour résoudre vos problèmes.",
        btn_all: "Tout",
        btn_admin: "Gestion",
        btn_media: "Média",
        btn_utility: "Utilitaire",
        btn_game: "Jeu",
        contact_title: "Contactez-moi",
        contact_desc: "Ouvert aux nouveaux projets.",
        btn_contact: "Envoyer Email",
        btn_close: "Fermer",
        btn_visit: "Voir le site",
        label_name: "Nom",
        label_email: "Email",
        label_message: "Message",
        btn_send: "Envoyer"
    },
    // 독일어
    de: {
        role: "Freiberuflicher Programmierer",
        based: "Lebt in den Philippinen",
        intro_title: "Hallo, ich bin Tony Cho.",
        intro_desc: "Ich entwickle Webanwendungen für Geschäftslösungen.",
        btn_all: "Alle",
        btn_admin: "Verwaltung",
        btn_media: "Medien",
        btn_utility: "Dienstprogramm",
        btn_game: "Spiel",
        contact_title: "Kontakt",
        contact_desc: "Offen für neue Projekte.",
        btn_contact: "E-Mail senden",
        btn_close: "Schließen",
        btn_visit: "Besuchen",
        label_name: "Name",
        label_email: "E-Mail",
        label_message: "Nachricht",
        btn_send: "Senden"
    },
    // 베트남어
    vi: {
        role: "Lập trình viên tự do",
        based: "Sống tại Philippines",
        intro_title: "Xin chào, tôi là Tony Cho.",
        intro_desc: "Tôi xây dựng các ứng dụng web giải quyết vấn đề kinh doanh.",
        btn_all: "Tất cả",
        btn_admin: "Quản lý",
        btn_media: "Truyền thông",
        btn_utility: "Tiện ích",
        btn_game: "Trò chơi",
        contact_title: "Liên hệ",
        contact_desc: "Sẵn sàng cho các dự án mới.",
        btn_contact: "Gửi Email",
        btn_close: "Đóng",
        btn_visit: "Ghé thăm",
        label_name: "Tên",
        label_email: "Email",
        label_message: "Tin nhắn",
        btn_send: "Gửi"
    },
    // 태국어
    th: {
        role: "โปรแกรมเมอร์ฟรีแลนซ์",
        based: "อาศัยอยู่ในฟิลิปปินส์",
        intro_title: "สวัสดี ผม Tony Cho",
        intro_desc: "ฉันสร้างเว็บแอพพลิเคชั่นเพื่อแก้ปัญหาทางธุรกิจ",
        btn_all: "ทั้งหมด",
        btn_admin: "การจัดการ",
        btn_media: "สื่อ",
        btn_utility: "ยูทิลิตี้",
        btn_game: "เกม",
        contact_title: "ติดต่อฉัน",
        contact_desc: "เปิดรับโปรเจกต์ใหม่",
        btn_contact: "ส่งอีเมล",
        btn_close: "ปิด",
        btn_visit: "เยี่ยมชมเว็บไซต์",
        label_name: "ชื่อ",
        label_email: "อีเมล",
        label_message: "ข้อความ",
        btn_send: "ส่ง"
    },
    // 포르투갈어 (브라질)
    pt: {
        role: "Programador Freelancer",
        based: "Baseado nas Filipinas",
        intro_title: "Olá, sou Tony Cho.",
        intro_desc: "Desenvolvo aplicações web que resolvem problemas reais.",
        btn_all: "Todos",
        btn_admin: "Gestão",
        btn_media: "Mídia",
        btn_utility: "Utilitário",
        btn_game: "Jogo",
        contact_title: "Contato",
        contact_desc: "Aberto a novos projetos.",
        btn_contact: "Enviar Email",
        btn_close: "Fechar",
        btn_visit: "Visitar Site",
        label_name: "Nome",
        label_email: "Email",
        label_message: "Mensagem",
        btn_send: "Enviar"
    }
};
